# Generated by Django 5.2 on 2025-05-01 21:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('referencia_muestra', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Referencia Muestra')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de Video')),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Agregado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='api.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_agregado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(max_length=255, verbose_name='URL de Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto Alternativo')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es Principal')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Subida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['producto', 'orden', '-es_principal'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)')),
                ('ciudad_resenador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('ip_resenador', models.GenericIPAddressField(verbose_name='IP Reseñador')),
                ('fecha_hora_resena', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_hora_resena'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_usuario', models.GenericIPAddressField(verbose_name='IP Usuario')),
                ('tipo_reaccion', models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta')], max_length=10, verbose_name='Tipo de Reacción')),
                ('fecha_hora_reaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='api.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'ordering': ['-fecha_hora_reaccion'],
                'unique_together': {('producto', 'ip_usuario')},
            },
        ),
    ]
